--------------------------------------------------------
--  파일이 생성됨 - 목요일-9월-26-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TIPLIST
--------------------------------------------------------

  CREATE TABLE "ADMIN"."TIPLIST" 
   (	"NUM" NUMBER, 
	"ID" VARCHAR2(20 BYTE), 
	"PASSWD" VARCHAR2(20 BYTE), 
	"SUBJECT" VARCHAR2(20 BYTE), 
	"CONTENT" VARCHAR2(20 BYTE), 
	"READCOUNT" NUMBER, 
	"COMMCOUNT" NUMBER, 
	"IP" VARCHAR2(20 BYTE), 
	"REG_DATE" VARCHAR2(20 BYTE), 
	"RE_REF" NUMBER, 
	"RE_LEV" NUMBER, 
	"RE_SEQ" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "ADMIN"."TIPLIST"."NUM" IS '글번호';
   COMMENT ON COLUMN "ADMIN"."TIPLIST"."ID" IS '아이디';
   COMMENT ON COLUMN "ADMIN"."TIPLIST"."PASSWD" IS '패스워드';
   COMMENT ON COLUMN "ADMIN"."TIPLIST"."SUBJECT" IS '글제목';
   COMMENT ON COLUMN "ADMIN"."TIPLIST"."CONTENT" IS '글내용';
   COMMENT ON COLUMN "ADMIN"."TIPLIST"."READCOUNT" IS '글조회수';
   COMMENT ON COLUMN "ADMIN"."TIPLIST"."COMMCOUNT" IS '글댓글수';
   COMMENT ON COLUMN "ADMIN"."TIPLIST"."IP" IS '작성자IP';
   COMMENT ON COLUMN "ADMIN"."TIPLIST"."REG_DATE" IS '글작성일';
REM INSERTING into ADMIN.TIPLIST
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index BOARD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."BOARD_PK" ON "ADMIN"."TIPLIST" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TIPLIST
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TIPLIST" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."TIPLIST" ADD CONSTRAINT "BOARD_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ADMIN"."TIPLIST" MODIFY ("NUM" NOT NULL ENABLE);
