--------------------------------------------------------
--  파일이 생성됨 - 목요일-9월-26-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TIPBOARD
--------------------------------------------------------

  CREATE TABLE "ADMIN"."TIPBOARD" 
   (	"NUM" NUMBER, 
	"ID" VARCHAR2(20 BYTE), 
	"PASSWD" VARCHAR2(20 BYTE), 
	"SUBJECT" VARCHAR2(200 BYTE), 
	"CONTENT" CLOB, 
	"READCOUNT" NUMBER, 
	"COMMCOUNT" NUMBER, 
	"IP" VARCHAR2(20 BYTE), 
	"REG_DATE" DATE, 
	"RE_REF" NUMBER, 
	"RE_LEV" NUMBER, 
	"RE_SEQ" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "ADMIN"."TIPBOARD"."NUM" IS '글번호';
   COMMENT ON COLUMN "ADMIN"."TIPBOARD"."ID" IS '아이디';
   COMMENT ON COLUMN "ADMIN"."TIPBOARD"."PASSWD" IS '패스워드';
   COMMENT ON COLUMN "ADMIN"."TIPBOARD"."SUBJECT" IS '글제목';
   COMMENT ON COLUMN "ADMIN"."TIPBOARD"."CONTENT" IS '글내용';
   COMMENT ON COLUMN "ADMIN"."TIPBOARD"."READCOUNT" IS '조회수';
   COMMENT ON COLUMN "ADMIN"."TIPBOARD"."COMMCOUNT" IS '댓글수';
   COMMENT ON COLUMN "ADMIN"."TIPBOARD"."IP" IS '작성자IP';
   COMMENT ON COLUMN "ADMIN"."TIPBOARD"."REG_DATE" IS '글작성일';
   COMMENT ON COLUMN "ADMIN"."TIPBOARD"."RE_REF" IS '글 그룹';
   COMMENT ON COLUMN "ADMIN"."TIPBOARD"."RE_LEV" IS '글 들여쓰기 레벨';
   COMMENT ON COLUMN "ADMIN"."TIPBOARD"."RE_SEQ" IS '같은 글그룹 안에서의 글번호';
REM INSERTING into ADMIN.TIPBOARD
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index TIPLIST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."TIPLIST_PK" ON "ADMIN"."TIPBOARD" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TIPBOARD
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TIPBOARD" ADD CONSTRAINT "TIPLIST_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ADMIN"."TIPBOARD" MODIFY ("NUM" NOT NULL ENABLE);
